# Generated by Django 4.2 on 2023-04-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
