# Generated by Django 4.2 on 2023-04-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_time',
            new_name='preparation_time_in_minutes',
        ),
    ]
