# Generated by Django 4.2 on 2023-05-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('preparation_time_in_minutes_min', models.PositiveIntegerField()),
                ('preparation_time_in_minutes_max', models.PositiveIntegerField()),
                ('level', models.CharField(choices=[('easy', 'EASY'), ('medium', 'MEDIUM'), ('hard', 'HARD')], max_length=6)),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
    ]
