# Generated by Django 4.2 on 2023-05-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='level',
            field=models.CharField(choices=[('easy', 'leicht'), ('medium', 'mittel'), ('hard', 'schwer')], max_length=6),
        ),
    ]
