# Generated by Django 4.2 on 2023-05-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_search_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='preparation_time_in_minutes_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='preparation_time_in_minutes_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
