# Generated by Django 4.2 on 2023-05-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipe_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='level',
            field=models.CharField(blank=True, choices=[('easy', 'leicht'), ('medium', 'mittel'), ('hard', 'schwer')], max_length=6),
        ),
    ]
