# Generated by Django 4.2 on 2023-05-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_search_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serving_size',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(verbose_name='Zubereitung'),
        ),
    ]
