# Generated by Django 4.2 on 2023-05-16 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0015_recipe_serving_size_alter_recipe_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeToShoppinglist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('recipes', models.ManyToManyField(through='recipes.RecipeToShoppinglist', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recipetoshoppinglist',
            name='shoppinglist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.shoppinglist'),
        ),
    ]
