# Generated by Django 4.2 on 2023-05-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_recipetoshoppinglist_shoppinglist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='preparation_time_in_minutes_min',
        ),
    ]
