# Generated by Django 4.2 on 2023-06-11 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0018_tag_tagtorecipe_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='favored_by',
            field=models.ManyToManyField(related_name='recipes_favored', through='recipes.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
