# Generated by Django 4.2 on 2023-07-02 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_recipe_created_by_alter_recipe_favored_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('is_bought', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='recipes',
        ),
        migrations.DeleteModel(
            name='RecipeToShoppinglist',
        ),
        migrations.AddField(
            model_name='shoppinglistingredient',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.shoppinglist'),
        ),
    ]
