# Generated by Django 4.2 on 2023-07-02 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_shoppinglistingredient_remove_shoppinglist_recipes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistingredient',
            name='ingredient',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shoppinglistingredient',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.shoppinglist'),
        ),
    ]
