# Generated by Django 4.2 on 2023-07-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_shoppinglistingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppinglistingredient',
            unique_together={('ingredient', 'unit', 'shopping_list')},
        ),
    ]
